import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#202c39]`}>
        <main className="flex flex-col items-center">
          <div className="relative z-0 w-full h-screen flex items-center justify-center">
            <div className="saturn">
              <div className="clouds"></div>
              <div className="planet"></div>
              <div className="ring"></div>
              <div className="up"></div>
            </div>
            <div className="absolute inset-0 flex justify-center items-center z-10">
              {children}
            </div>
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
